import test from 'node:test'
import assert from 'node:assert/strict'
import { LocalProvider, shouldAcceptSnapshot } from '../src/console/localProvider'
import { percent, riskText } from '../src/console/presentation'
test('offline fixture and server units',async()=>{const old=globalThis.fetch;globalThis.fetch=()=>{throw Error('network forbidden')};try{const p=new LocalProvider();await p.loadScene(5);const s=await p.getSnapshot();assert.equal(s.incidents[0].risk,89);assert.equal(percent(s.incidents[0].confidence),'92%');assert.equal((await p.getClip('INC-032')).available,false);assert.equal(s.configured_cameras,9)}finally{globalThis.fetch=old}})
test('ACK idempotency and closed rank',async()=>{const p=new LocalProvider();await p.loadScene(5);const a=await p.ack('INC-032',{action:'verify'},'k');assert.deepEqual(await p.ack('INC-032',{action:'verify'},'k'),a);assert.equal(a.incident.rank,null);assert.equal((await p.getSnapshot()).active_count,2);await assert.rejects(()=>p.ack('INC-032',{action:'dismiss'},'k'))})
test('concurrent replay is one mutation',async()=>{const p=new LocalProvider();await p.loadScene(3);const before=(await p.getSnapshot()).revision;const [a,b]=await Promise.all([p.ack('INC-032',{action:'verify'},'k'),p.ack('INC-032',{action:'verify'},'k')]);assert.deepEqual(a,b);assert.equal((await p.getSnapshot()).revision,before+1)})
test('review independent of risk and dispatch is intent',async()=>{const p=new LocalProvider();await p.loadScene(5);await p.ack('INC-032',{action:'request_dispatch'},'d');await p.ack('INC-032',{action:'needs_review'},'r');assert.equal((await p.getIncident('INC-032')).risk,89);assert.equal((await p.getSnapshot()).active_count,3);await assert.rejects(()=>p.ack('INC-032',{action:'handover'},'h'));await p.ack('INC-032',{action:'handover',to_operator:'op2'},'h2');assert.equal((await p.getIncident('INC-032')).assigned_operator,'op2')})
test('unknown restore does not fabricate evidence or risk',async()=>{const p=new LocalProvider();await p.loadScene(2);await p.restore('SUP-001','r');await p.restore('SUP-001','r');const s=await p.getSnapshot();assert.equal(s.active_count,1);assert.equal(s.incidents[0].risk,null);assert.deepEqual(s.incidents[0].evidence,[]);assert.equal(riskText(null),'미측정');assert.equal(percent(null),'미측정')})
test('terminal dismissal',async()=>{const p=new LocalProvider();await p.loadScene(3);await p.ack('INC-032',{action:'dismiss'},'d');await assert.rejects(()=>p.ack('INC-032',{action:'verify'},'v'))})
test('epoch reset and immutable copies',async()=>{const p=new LocalProvider();await p.loadScene(5);const a=await p.getSnapshot();const b=structuredClone(a);b.revision--;assert.equal(shouldAcceptSnapshot(a,b),false);assert.equal(shouldAcceptSnapshot(a,b,true),true);b.server_instance_id='new';assert.equal(shouldAcceptSnapshot(a,b),true);a.incidents[0].risk=0;assert.equal((await p.getSnapshot()).incidents[0].risk,89)})
